export type { CapabilitySource } from './sources/capability-source.js'
export { NullCapabilitySource } from './sources/null-capability-source.js'
export { LocalPluginSource } from './sources/local-plugin-source.js'
export { LearningTriggerHandler } from './trigger/learning-trigger-handler.js'
export { CapabilityValidator } from './validation/capability-validator.js'
export { SandboxValidator } from './validation/sandbox-validator.js'
export { AcquisitionPolicyEngine } from './policy/acquisition-policy-engine.js'
export type { AcquisitionStore } from './store/acquisition-store.js'
export { NullAcquisitionStore } from './store/null-acquisition-store.js'
export { JsonAcquisitionStore } from './store/json-acquisition-store.js'
export { CapabilityAcquisitionEngine } from './engine/capability-acquisition-engine.js'
export type { AcquisitionResult } from './engine/capability-acquisition-engine.js'
