export const REASONING_VERSION = '0.1.0'

export { EvidenceCollector, EvidenceNormalizer, EvidenceGraphBuilder } from './evidence/evidence-collector.js'
export type { EvidenceInput } from './evidence/evidence-collector.js'
export { InferenceEngine } from './inference/inference-engine.js'
export type { InferenceRule } from './inference/inference-rule.js'
export { ProviderLatencyRule, CapabilityFailureRule, NetworkCorrelationRule, PlanningDeficiencyRule } from './inference/inference-rules.js'
export { HypothesisGenerator, HypothesisRanker } from './hypothesis/hypothesis-generator.js'
export { RecommendationEngine } from './engine/recommendation-engine.js'
export { ReasoningEngine } from './engine/reasoning-engine.js'
export { ReasoningExplainer } from './engine/reasoning-explainer.js'
export { ReasoningPolicyEngine } from './policy/reasoning-policy-engine.js'
export type { ReasoningStore } from './store/reasoning-store.js'
export { NullReasoningStore, applyQuery } from './store/null-reasoning-store.js'
export { JsonReasoningStore } from './store/json-reasoning-store.js'
