export const RECOMMENDER_VERSION = '0.1.0'

export type { RecommendationStrategy, RecommendationCandidate } from './strategies/recommendation-strategy.js'
export { GraphExpansionStrategy } from './strategies/graph-expansion.js'
export { AlternativeStrategy } from './strategies/alternatives.js'
export { CompanionToolStrategy } from './strategies/companion-tools.js'
export { CorpusFrequencyStrategy } from './strategies/corpus-frequency.js'
export { RecommendationMerger } from './merger/recommendation-merger.js'
export { RecommendationRanker } from './ranking/recommendation-ranker.js'
export { ExplanationBuilder } from './ranking/explanation-builder.js'
export { NullRecommendationStore } from './store/null-store.js'
export type { RecommendationPolicy } from './policy/recommendation-policy.js'
export { DefaultRecommendationPolicy } from './policy/recommendation-policy.js'
export { LexicalAnchorResolver } from './resolver/anchor-resolver.js'
export { RecommendationEngine } from './engine/recommendation-engine.js'
export type { RecommendationEngineOptions } from './engine/recommendation-engine.js'
export { WorkflowStrategy } from './strategies/workflow-strategy.js'
