export { canonicalize, canonicalJson } from './canonicalizer.js'
export { semanticHash, auditHash } from './hasher.js'
export { buildSemanticProjection } from './semantic-projection.js'
export { parseLockfileYaml, LockfileValidatorImpl } from './parser.js'
export { SnapshotAssemblerImpl } from './snapshot-assembler.js'
export { LockfileGeneratorImpl } from './generator.js'
export { LockfileStoreImpl } from './store.js'
export { WorkspaceInspectors } from './inspectors.js'
export { LockDriftDetectorImpl } from './drift-detector.js'
export { LockAdmissionControllerImpl, LockfileLifecycleServiceImpl } from './admission-controller.js'
export { LockfileMigrationRegistry, V1IdentityMigration, executeMigration } from './migrator.js'
