import { join } from 'node:path'
import { readFile, writeFile, rename, unlink, open } from 'node:fs/promises'
import { dump as yamlDump, JSON_SCHEMA } from 'js-yaml'
import type { LockfileStore, RohinikLockfileV1 } from '@rohinik-org/lockfile-ir'
import { LockWriteError } from '@rohinik-org/lockfile-ir'
import { parseLockfileYaml } from './parser.js'
import { LockfileValidatorImpl } from './parser.js'

const LOCKFILE_NAME = 'rohinik.lock'
const LOCKFILE_TMP = 'rohinik.lock.rhk-tmp'
const HEADER = '# Generated by Rohinik. Do not edit manually.\n'

const validator = new LockfileValidatorImpl()

export class LockfileStoreImpl implements LockfileStore {
  async read(projectRoot: string): Promise<RohinikLockfileV1 | undefined> {
    const raw = await this.readRaw(projectRoot)
    if (raw === undefined) return undefined
    const parsed = parseLockfileYaml(raw)
    return validator.parse(parsed)
  }

  async readRaw(projectRoot: string): Promise<string | undefined> {
    const path = join(projectRoot, LOCKFILE_NAME)
    try {
      return await readFile(path, 'utf8')
    } catch (e: unknown) {
      if (isNodeError(e) && e.code === 'ENOENT') return undefined
      throw e
    }
  }

  async writeAtomic(projectRoot: string, lockfile: RohinikLockfileV1): Promise<void> {
    const lockPath = join(projectRoot, LOCKFILE_NAME)
    const tmpPath = join(projectRoot, LOCKFILE_TMP)

    // Serialize with deterministic field order
    const yaml = serializeLockfile(lockfile)

    try {
      // Write to tmp
      await writeFile(tmpPath, yaml, 'utf8')

      // fsync the tmp file
      const fd = await open(tmpPath, 'r+')
      try {
        await fd.sync()
      } finally {
        await fd.close()
      }

      // Validate by reading back
      const readBack = await readFile(tmpPath, 'utf8')
      const reparsed = parseLockfileYaml(readBack)
      validator.parse(reparsed)

      // fsync directory (best-effort — not supported on Windows)
      try {
        const dirFd = await open(projectRoot, 'r')
        try { await dirFd.sync() } finally { await dirFd.close() }
      } catch { /* best-effort */ }

      // Atomic rename
      await rename(tmpPath, lockPath)
    } catch (e) {
      // Clean up tmp on failure
      try { await unlink(tmpPath) } catch { /* ignore */ }
      if (e instanceof LockWriteError) throw e
      throw new LockWriteError(`Failed to write lockfile: ${String(e)}`)
    }
  }
}

function serializeLockfile(lockfile: RohinikLockfileV1): string {
  // Build a plain object with deterministic key order
  const ordered: Record<string, unknown> = {
    kind: lockfile.kind,
    lockVersion: lockfile.lockVersion,
    application: lockfile.application,
    runtime: lockfile.runtime,
    resolution: lockfile.resolution,
    capabilities: lockfile.capabilities,
    packages: lockfile.packages,
    dependencies: lockfile.dependencies,
    models: lockfile.models,
    infrastructure: lockfile.infrastructure,
    providers: lockfile.providers,
    configuration: lockfile.configuration,
    policies: lockfile.policies,
    semanticHash: lockfile.semanticHash,
    audit: lockfile.audit,
    auditHash: lockfile.auditHash,
  }
  if (lockfile.extensions !== undefined) {
    ordered['extensions'] = lockfile.extensions
  }
  const body = yamlDump(ordered, { schema: JSON_SCHEMA, lineWidth: 120, noRefs: true })
  return HEADER + body
}

function isNodeError(e: unknown): e is NodeJS.ErrnoException {
  return e instanceof Error && 'code' in e
}
