export const DAEMON_VERSION = '0.1.0'

export { DaemonHost } from './host/daemon-host.js'
export type { DaemonHostOptions } from './host/daemon-host.js'
export { SocketRuntimeTransport } from './ipc/socket-runtime-transport.js'
export { IpcServer } from './ipc/ipc-server.js'
export { IpcClient } from './ipc/ipc-client.js'
export { ProtocolCodec } from './ipc/protocol-codec.js'
export type { RuntimeTransport } from './ipc/runtime-transport.js'
export type { IpcRequestHandler } from './ipc/ipc-server.js'
export { RuntimeJournal } from './journal/runtime-journal.js'
export type { RuntimeJournalEntry, RuntimeJournalEventType } from './journal/runtime-journal.js'
export { ServiceRegistry, ServiceAdapter } from './registry/service-registry.js'
export type { RuntimeService } from './registry/runtime-service.js'
export { LifecycleManager } from './lifecycle/lifecycle-manager.js'
export { HealthMonitor } from './health/health-monitor.js'
export { DaemonPersistence } from './persistence/daemon-persistence.js'
export { ShutdownCoordinator } from './shutdown/shutdown-coordinator.js'
