export const DISTRIBUTED_VERSION = '0.1.0'

export { NodeRegistry } from './registry/node-registry.js'
export type { NodeSelectionDecision } from './registry/capability-directory.js'
export { CapabilityDirectory } from './registry/capability-directory.js'
export { NodeDiscovery } from './discovery/node-discovery.js'
export { DistributedScheduler } from './scheduler/distributed-scheduler.js'
export type { WorkflowFragment } from './scheduler/distributed-scheduler.js'
export { RemoteExecutor } from './executor/remote-executor.js'
export type { RemoteTransport, RemoteExecutionResult } from './executor/remote-executor.js'
export { ReplicationManager } from './replication/replication-manager.js'
export type { ReplicatableArtifactType } from './replication/replication-manager.js'
export { RemoteMemoryBridge } from './memory/remote-memory-bridge.js'
export type { RemoteMemoryEntry } from './memory/remote-memory-bridge.js'
export { ClusterCoordinator } from './coordinator/cluster-coordinator.js'
export { ClusterPolicyEngine } from './policy/cluster-policy-engine.js'
export type { PolicyDecision, ClusterOperation } from './policy/cluster-policy-engine.js'
export { ClusterJournal } from './journal/cluster-journal.js'
export type { ClusterStore } from './store/cluster-store.js'
export { NullClusterStore, applyQuery } from './store/null-cluster-store.js'
