export const REFLECTION_VERSION = '0.1.0'

export { NullReflectionStore, applyQuery } from './store/null-reflection-store.js'
export { JsonReflectionStore } from './store/json-reflection-store.js'
export type { ReflectionStore } from './store/reflection-store.js'
export { ReflectionAnalyzer } from './analyzer/reflection-analyzer.js'
export { RootCauseAnalyzer } from './critics/root-cause-analyzer.js'
export { PlanCritic, ExecutionCritic, ProviderCritic } from './critics/critics.js'
export type { ReflectionCritic } from './critics/reflection-critic.js'
export { RecommendationEngine } from './engine/recommendation-engine.js'
export { ReflectionEngine } from './engine/reflection-engine.js'
export { ReflectionPolicyEngine } from './policy/reflection-policy-engine.js'
