export const HOST_DISCOVERY_VERSION = '0.1.0'
export type { HostDetector } from './detectors/host-detector.js'
export { BinaryDetector } from './detectors/binary-detector.js'
export { PythonDetector } from './detectors/binary/python-detector.js'
export { NodeDetector } from './detectors/binary/node-detector.js'
export { GitDetector } from './detectors/binary/git-detector.js'
export { DockerDetector } from './detectors/binary/docker-detector.js'
export { JavaDetector } from './detectors/binary/java-detector.js'
export { GoDetector } from './detectors/binary/go-detector.js'
export { RustDetector } from './detectors/binary/rust-detector.js'
export { DotnetDetector } from './detectors/binary/dotnet-detector.js'
export { BashDetector } from './detectors/binary/bash-detector.js'
export { PowerShellDetector } from './detectors/binary/powershell-detector.js'
export { GhDetector } from './detectors/binary/gh-detector.js'
export { OllamaDetector } from './detectors/runtime/ollama-detector.js'
export { CudaDetector } from './detectors/runtime/cuda-detector.js'
export { VSCodeDetector } from './detectors/ide/vscode-detector.js'
export { DefaultHostClassifier } from './classifier/host-classifier.js'
export type { HostClassifier } from './classifier/host-classifier.js'
export { HostDiscoveryEngine } from './discovery-engine.js'
export { DiscoveryStore } from './discovery-store.js'
export { HostProvider } from './host-provider.js'
